# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Fabric Properties
minecraft_version=26.2
parchment_version=1.21.1:2024.11.17
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

fabric_api_version=0.152.2+26.2

# Mod Properties
mod_id=wilderdelights
mod_name=Wilder Delights
mod_license=MIT
mod_version=1.0.1-26
mod_authors=LilithElder
mod_description=A Farmer's Delight and Wilder Wild compatibility add-on!
maven_group=com.lilithelder
archives_base_name=wilderdelights